### ISSUE TITLE
wm同级download文件夹,该文件未生成

### ISSUE THREAD

**Issue by 2317758226** [HellSakura/wm#1]
输入课程名，并点击确认后，未生成wm同级download文件夹
![image](https://user-images.githubusercontent.com/82520465/114720201-65815100-9d6a-11eb-984e-9644ff60858c.png)
![image](https://user-images.githubusercontent.com/82520465/114720307-7fbb2f00-9d6a-11eb-8cd9-bc524aa3033b.png)

求大佬指教

**Comment by HellSakura** [comment]
请下载 [release](https://github.com/HellSakura/wm/releases)中的``wm.exe`` 可执行文件，运行后会在该可执行文件同级目录下生成download文件夹    
![image](https://user-images.githubusercontent.com/43169031/115675097-dd5e0580-a380-11eb-8212-cf908d9e787b.png)
我这里测试是正常下载的，你这是直接下载了源码    
> 当然，你也可以自行编译    
安装 Go 和 Yarn 后执行`` ./build.sh`` 在 dist 文件夹得到可执行文件与 index.js 脚本文件。

**Comment by 2317758226** [comment]
好的,已经实现了,非常感谢你的程序


| |
袁林
|
|
***@***.***
|
签名由网易邮箱大师定制
在2021年4月22日 ***@***.***> 写道：

请下载 release中的wm.exe 可执行文件，运行后会在该可执行文件同级目录下生成download文件夹

我这里测试是正常下载的，你这是直接下载了源码

当然，你也可以自行编译
安装 Go 和 Yarn 后执行 ./build.sh 在 dist 文件夹得到可执行文件与 index.js 脚本文件。
