### ISSUE TITLE
【求助】大佬提供的M3U8下载链接失效了，且新版下载器不能拖文件进去

### ISSUE THREAD

**Issue by xiaozhi07** [HellSakura/wm#2]
【求助】大佬提供的M3U8下载链接失效了，且新版下载器不能拖文件进去

**Comment by HellSakura** [comment]
M3U8下载器仓库链接[https://github.com/nilaoda/N_m3u8DL-CLI/releases](url)

至于你说的拖动文件问题，可以在上述仓库中的releases中找到旧版本去尝试一下
